# Generated by Django 4.1 on 2022-08-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='keywords',
        ),
    ]
