# Generated by Django 4.1 on 2022-08-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_discount_product_discount_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_status',
        ),
    ]
