# Generated by Django 4.1 on 2022-08-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_image_productimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('smtpserver', models.CharField(blank=True, max_length=50, null=True)),
                ('smtpemail', models.CharField(blank=True, max_length=50, null=True)),
                ('smtppassword', models.CharField(blank=True, max_length=10, null=True)),
                ('smtpport', models.CharField(blank=True, max_length=5, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('instegram', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
