# Generated by Django 4.0.1 on 2022-08-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_shopcart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productCart', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
