# Generated by Django 4.0.1 on 2022-08-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_shopcart_product_alter_shopcart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('orderd', 'orderd')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
