# Generated by Django 4.0.1 on 2022-08-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_shopcart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('orderd', 'orderd')], default='pending', max_length=50),
        ),
    ]
