# Generated by Django 4.0.1 on 2022-08-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_variant_image_alter_variant_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minamount',
        ),
    ]
